import os
from core.mcp_client import call_mcp_tool

def setup_detection_engineering_parser(subparsers):
    """Sets up the argparse subcommands for the 'detection' domain."""
    det_parser = subparsers.add_parser("detection", help="Manage Detection Rules and Reference Lists")
    det_subparsers = det_parser.add_subparsers(dest="det_command", required=True)

    # list_rules
    list_rules_parser = det_subparsers.add_parser("list-rules", help="List all YARA-L rules")
    list_rules_parser.add_argument("--project-id", default=os.environ.get("SECOPS_PROJECT_ID"), help="GCP project ID")
    list_rules_parser.add_argument("--customer-id", default=os.environ.get("SECOPS_CUSTOMER_ID"), help="Chronicle customer ID")
    list_rules_parser.add_argument("--region", default=os.environ.get("SECOPS_REGION"), help="Chronicle region")
    list_rules_parser.add_argument("--page-size", type=int, help="Maximum number of rules to return")
    list_rules_parser.add_argument("--filter", help="Filter string")

    # list_rule_errors
    list_errors_parser = det_subparsers.add_parser("list-rule-errors", help="Lists execution errors for a specific rule")
    list_errors_parser.add_argument("--project-id", default=os.environ.get("SECOPS_PROJECT_ID"), help="GCP project ID")
    list_errors_parser.add_argument("--customer-id", default=os.environ.get("SECOPS_CUSTOMER_ID"), help="Chronicle customer ID")
    list_errors_parser.add_argument("--region", default=os.environ.get("SECOPS_REGION"), help="Chronicle region")
    list_errors_parser.add_argument("--rule-id", required=True, help="The rule ID")
    list_errors_parser.add_argument("--page-size", type=int, help="Maximum number of errors to return")

    # create_rule
    create_rule_parser = det_subparsers.add_parser("create-rule", help="Create a new YARA-L rule")
    create_rule_parser.add_argument("--project-id", default=os.environ.get("SECOPS_PROJECT_ID"), help="GCP project ID")
    create_rule_parser.add_argument("--customer-id", default=os.environ.get("SECOPS_CUSTOMER_ID"), help="Chronicle customer ID")
    create_rule_parser.add_argument("--region", default=os.environ.get("SECOPS_REGION"), help="Chronicle region")
    create_rule_parser.add_argument("--rule", required=True, help="The raw YARA-L rule text")

    # validate_rule
    validate_rule_parser = det_subparsers.add_parser("validate-rule", help="Validate YARA-L 2.0 rule text syntax and compilation")
    validate_rule_parser.add_argument("--project-id", default=os.environ.get("SECOPS_PROJECT_ID"), help="GCP project ID")
    validate_rule_parser.add_argument("--customer-id", default=os.environ.get("SECOPS_CUSTOMER_ID"), help="Chronicle customer ID")
    validate_rule_parser.add_argument("--region", default=os.environ.get("SECOPS_REGION"), help="Chronicle region")
    validate_rule_parser.add_argument("--rule", required=True, help="The raw YARA-L rule text to validate")

    # list_rule_detections
    list_rule_detections_parser = det_subparsers.add_parser("list-rule-detections", help="Retrieves historical detections generated by a specific rule")
    list_rule_detections_parser.add_argument("--project-id", default=os.environ.get("SECOPS_PROJECT_ID"), help="GCP project ID")
    list_rule_detections_parser.add_argument("--customer-id", default=os.environ.get("SECOPS_CUSTOMER_ID"), help="Chronicle customer ID")
    list_rule_detections_parser.add_argument("--region", default=os.environ.get("SECOPS_REGION"), help="Chronicle region")
    list_rule_detections_parser.add_argument("--rule-id", required=True, help="Unique ID of the rule to list detections for")
    list_rule_detections_parser.add_argument("--alert-state", help="Filter by alert state (UNSPECIFIED, NOT_ALERTING, ALERTING)")
    list_rule_detections_parser.add_argument("--start-time", help="Start of the time range in ISO 8601 format")
    list_rule_detections_parser.add_argument("--end-time", help="End of the time range in ISO 8601 format")
    list_rule_detections_parser.add_argument("--list-basis", help="Time basis (LIST_BASIS_UNSPECIFIED, DETECTION_TIME, CREATED_TIME)")
    list_rule_detections_parser.add_argument("--page-size", type=int, help="Maximum number of detections to return")
    list_rule_detections_parser.add_argument("--page-token", help="Page token from a previous call")

    # get_rule
    get_rule_parser = det_subparsers.add_parser("get-rule", help="Get a specific YARA-L rule")
    get_rule_parser.add_argument("--project-id", default=os.environ.get("SECOPS_PROJECT_ID"), help="GCP project ID")
    get_rule_parser.add_argument("--customer-id", default=os.environ.get("SECOPS_CUSTOMER_ID"), help="Chronicle customer ID")
    get_rule_parser.add_argument("--region", default=os.environ.get("SECOPS_REGION"), help="Chronicle region")
    get_rule_parser.add_argument("--rule-id", required=True, help="The rule ID")
    get_rule_parser.add_argument("--view", help="The view to use (BASIC, FULL, REVISION_METADATA_ONLY, CONFIG_ONLY, TRENDS)")

def execute_detection_engineering_command(args):
    """Routes the command to the appropriate MCP tool call."""
    if args.det_command == "list-rules":
        arguments = {
            "projectId": args.project_id,
            "customerId": args.customer_id,
            "region": args.region
        }
        if getattr(args, 'page_size', None): arguments["pageSize"] = args.page_size
        if getattr(args, 'filter', None): arguments["filter"] = args.filter
        return call_mcp_tool(args.project_id, args.region, "list_rules", arguments)

    elif args.det_command == "list-rule-errors":
        arguments = {
            "projectId": args.project_id,
            "customerId": args.customer_id,
            "region": args.region,
            "ruleId": args.rule_id
        }
        if getattr(args, 'page_size', None): arguments["pageSize"] = args.page_size
        return call_mcp_tool(args.project_id, args.region, "list_rule_errors", arguments)

    elif args.det_command == "create-rule":
        arguments = {
            "projectId": args.project_id,
            "customerId": args.customer_id,
            "region": args.region,
            "rule": args.rule
        }
        return call_mcp_tool(args.project_id, args.region, "create_rule", arguments)

    elif args.det_command == "get-rule":
        arguments = {
            "projectId": args.project_id,
            "customerId": args.customer_id,
            "region": args.region,
            "ruleId": args.rule_id
        }
        if getattr(args, 'view', None): arguments["view"] = args.view
        return call_mcp_tool(args.project_id, args.region, "get_rule", arguments)

    elif args.det_command == "validate-rule":
        arguments = {
            "projectId": args.project_id,
            "customerId": args.customer_id,
            "region": args.region,
            "rule": args.rule
        }
        return call_mcp_tool(args.project_id, args.region, "validate_rule", arguments)

    elif args.det_command == "list-rule-detections":
        arguments = {
            "projectId": args.project_id,
            "customerId": args.customer_id,
            "region": args.region,
            "ruleId": args.rule_id
        }
        if getattr(args, 'alert_state', None): arguments["alertState"] = args.alert_state
        if getattr(args, 'start_time', None): arguments["startTime"] = args.start_time
        if getattr(args, 'end_time', None): arguments["endTime"] = args.end_time
        if getattr(args, 'list_basis', None): arguments["listBasis"] = args.list_basis
        if getattr(args, 'page_size', None): arguments["pageSize"] = args.page_size
        if getattr(args, 'page_token', None): arguments["pageToken"] = args.page_token
        return call_mcp_tool(args.project_id, args.region, "list_rule_detections", arguments)

    else:
        raise RuntimeError(f"Unhandled command '{args.det_command}'")
